highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://cv.peterskaronis.com/
author: Peter Skaronis

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: 
title: Peter Skaronis Resume
name: Peter Skaronis
email: Secure Email
email_full: mailto:pskaronis@protonmail.com
website: peterskaronis.com
website_full: http://cv.peterskaronis.com/
github: techimpossible
twitter: Peter_Skaronis
tel: +1 347 234 5428
tel_full: tel:+13472345428
google_maps: 'https://www.google.co.uk/maps/place/616+Corporate+Way,+Valley+Cottage,+NY+10989,+USA/@41.1275786,-73.9479478,17z/data=!3m1!4b1!4m2!3m1!1s0x89c2c22307900a73:0xb6ce23bafbc5465a'
address: 616 Corporate Way, ST 2-4460
postcode: 10989
city: Valley Cottage, NY
country: USA
google_analytics: UA-45619220-1

# needed for travis-ci build
exclude: [vendor]
